//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_Management_Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sales
    {
        public int ID { get; set; }
        public string Sell_Name { get; set; }
        public string Sell_Cus { get; set; }
        public Nullable<double> Sell_Price { get; set; }
        public Nullable<double> Sell_QT { get; set; }
        public Nullable<double> Sell_TPrice { get; set; }
        public Nullable<System.DateTime> Sell_Date { get; set; }
    }
}
